version: "3.9"

services:
  app:
    build: .
    container_name: enyo-test-app
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
      - cache
    depends_on:
      - database
      - cache

  database:
    image: mysql
    container_name: enyo-test-mysql
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_DATABASE=dbenyo
      - MYSQL_USER=admin
      - MYSQL_ROOT_PASSWORD=a12345z
    volumes:
      - database:/var/lib/mysql

  cache:
    image: redis:alpine
    container_name: enyo-test-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - cache:/data/redis

volumes:
  database:
    driver: local
  cache:
    driver: local